name: Lint and tests
on: push
jobs:
  lint:
    name: Lint sources and compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Run checks
        run: ./gradlew check

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Run checks
        run: ./gradlew test
